### ISSUE TITLE
Info.plist on RN42 uses $(PRODUCT_BUNDLE_IDENTIFIER)

### ISSUE THREAD

**Issue by kenmaca** [kyle-ssg/react-native-app-id#1]
Hi,

Thanks for the tool. Just reporting that it fails on RN42 because `Could not detect ios app id from plist`. This is because the Bundle ID found in `project.pbxproj` does not appear in `Info.plist` anymore, but now `$(PRODUCT_BUNDLE_IDENTIFIER)` on RN42 (I think even as early as RN40, but could be wrong).

You can fix this by just not `reject`ing the `Promise` when that step fails.

Also, unrelated: but this tool doesn't fix up the Android package names/file structure. I think it's harmless, but seeing the old name bothers me.

**Comment by kyle-ssg** [comment]
Hey @kenmaca, thanks for the headsup about the bundle ID - will fix. 

I purposefully didn't change the android structure as it doesn't really affect anything, its not really that hard to fix but I didn't see enough value in spending time on it. I'd gladly accept a PR on it as I can appreciate it would bother people.

**Comment by tylermurry** [comment]
I am running into the same issue. Are there plans to release a fix?

**Comment by kyle-ssg** [comment]
Spent a bit of time on this, fixed in latest release
