### ISSUE TITLE
Display warning when firebase is added to the project

### ISSUE THREAD

**Issue by kaladivo** [kyle-ssg/react-native-app-id#4]
When app id is changed in project that has google firebase integrated `google-services.json` file needs to be regenerated in firebase administration. It would be great if this script show some kind of warning to alert developer to reconfigurate firebase...

**Comment by kyle-ssg** [comment]
This could apply to quite a few services that get tied to an app bundle ID. I could detect 3rd party libs used in a project but I'd say this is very much out of scope
